### PR TITLE
Tim Harrison submission

### PR DESCRIPTION
**Pull request by trwh**

### CODE REVIEW

**Comment by tansaku** [comment]
A really great start here Tim, tests all green - lovely! 100% test coverage - awesome!

Some things you should think about:

* hound issues --> line too long - fix those up
* needs merge for CI to run: https://help.github.com/articles/syncing-a-fork/
* not sure why you are using ruby 2.1.5 - prefer the latest, e.g. 2.2.3
* you've updated the readme which is great, but you could go further - in particular I'd like to see a transcript of how to run the program from irb
* you shouldn't need to use require_relative - require should be fine for spec_helper and for anything in the lib dir (in takeaway_spec)
* takeaway_spec line 7 not two spaced indented - get OCD about that
* takeaway class is hardcoded to Dish - you could ease that relationship with some dependency injection?

Here also for your edification are some issues I got from running the [reek](https://github.com/troessner/reek) (`gem install reek ; reek -U`) code smell tool on it:

> → reek -U
lib/dish.rb -- 1 warning:
  [4]:Dish#quantity is a writable attribute (Attribute) [https://github.com/troessner/reek/blob/master/docs/Attribute.md]
lib/meal.rb -- 1 warning:
  [15]:Meal#total has the variable name 'i' (UncommunicativeVariableName) [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md]
lib/takeaway.rb -- 5 warnings:
  [42]:Takeaway#check_price doesn't depend on instance state (maybe move it to another class?) (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
  [27]:Takeaway#order contains iterators nested 2 deep (NestedIterators) [https://github.com/troessner/reek/blob/master/docs/Nested-Iterators.md]
  [22]:Takeaway#order has approx 7 statements (TooManyStatements) [https://github.com/troessner/reek/blob/master/docs/Too-Many-Statements.md]
  [15]:Takeaway#see has the variable name 'i' (UncommunicativeVariableName) [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md]
  [16, 17, 19]:Takeaway#see refers to list more than self (maybe move it to another class?) (FeatureEnvy) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]

Overall some really good work here.  Don't be intimidated by the above list, you've done really well, but I want to give you all the help I can to take things to the next level :-)  There are a few other things as well, but have a go at fixing up some of the above, we'll do another round of feedback and then and we'll see about getting you a sticker :-)

:construction:

**Comment by trwh** [comment]
Hi Tansaku, many thanks! I've replied inline below, let me know if anything more is needed for a pass. :)

Thanks again,

Tim

A really great start here Tim, tests all green - lovely! 100% test coverage - awesome!

Some things you should think about:

* hound issues --> line too long - fix those up __OK, done, begrudgingly though as I think this reduces readability and editability (is that a word!?) and people can / should use text editors with word wrap. :) ;)__
* needs merge for CI to run: https://help.github.com/articles/syncing-a-fork/ __I don't have permissions to do this, I think?__ `Only those with write access to this repository can merge pull requests.`
* not sure why you are using ruby 2.1.5 - prefer the latest, e.g. 2.2.3 __It's the one that comes with OS X Yosemite, nothing was broken / missing so I defaulted to not changing.__
* you've updated the readme which is great, but you could go further - in particular I'd like to see a   transcript of how to run the program from irb __Added.__
* you shouldn't need to use require_relative - require should be fine for spec_helper and for anything in the lib dir (in takeaway_spec) __Fixed.__
* takeaway_spec line 7 not two spaced indented - get OCD about that __Fixed.__
* takeaway class is hardcoded to Dish - you could ease that relationship with some dependency injection? __Done what I think is right, is this OK? I did it on the `order` method too.__
* Here also for your edification are some issues I got from running the reek (gem install reek ; reek -U) code smell tool on it:

> → reek -U
> lib/dish.rb -- 1 warning:
> [4]:Dish#quantity is a writable attribute (Attribute) [https://github.com/troessner/reek/blob/master/docs/Attribute.md]
> lib/meal.rb -- 1 warning:
> [15]:Meal#total has the variable name 'i' (UncommunicativeVariableName) __Fixed.__ [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md]
> lib/takeaway.rb -- 5 warnings:
> [42]:Takeaway#check_price doesn't depend on instance state (maybe move it to another class?) (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
> [27]:Takeaway#order contains iterators nested 2 deep (NestedIterators) [https://github.com/troessner/reek/blob/master/docs/Nested-Iterators.md]
> [22]:Takeaway#order has approx 7 statements (TooManyStatements) [https://github.com/troessner/reek/blob/master/docs/Too-Many-Statements.md]
> [15]:Takeaway#see has the variable name 'i' (UncommunicativeVariableName) __Fixed.__ [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md]
> [16, 17, 19]:Takeaway#see refers to list more than self (maybe move it to another class?) (FeatureEnvy) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]

Overall some really good work here. Don't be intimidated by the above list, you've done really well, but I want to give you all the help I can to take things to the next level :-) There are a few other things as well, but have a go at fixing up some of the above, we'll do another round of feedback and then and we'll see about getting you a sticker :-)

:construction:

**Comment by tansaku** [comment]
Hi @trwh .  Well done for responding to my points.  My responses to your responses below :-)

* hound issues --> line too long - fix those up 
  * OK, done, begrudgingly though as I think this reduces readability and editability (is that a word!?) and people can / should use text editors with word wrap. :) ;)

I am going to have to disagree with you here.  Word wrap is shunned in code because it makes the indenting difficult to follow, and indenting will save you hours of work.  If you want to be a professional developer get used to keeping your line length down.

* needs merge for CI to run: https://help.github.com/articles/syncing-a-fork/ 
  * I don't have permissions to do this, I think? Only those with write access to this repository can merge pull requests.

You do have permission for the above - I'm not asking you to merge your pull request into our repo (that you can't do).  I'm asking you to pull the upstream changes from our repo into your fork - that you can, and need to be able to do as it is an important skill for a developer.

* not sure why you are using ruby 2.1.5 - prefer the latest, e.g. 2.2.3 
  * It's the one that comes with OS X Yosemite, nothing was broken / missing so I defaulted to not changing.

Understood - watch out for defaults like that - they can get you into trouble :-)


* you've updated the readme which is great, but you could go further - in particular I'd like to see a transcript of how to run the program from irb 
  * Added.

Great - can you go further and update the entire README to reflect what you are presenting to us?  At the moment most of the text is a challenge description.  Have the README describe what you are submitting and your thoughts about it.

* you shouldn't need to use require_relative - require should be fine for spec_helper and for anything in the lib dir (in takeaway_spec) 
  * Fixed.

I'm still seeing require_relative in some of your specs

* takeaway_spec line 7 not two spaced indented - get OCD about that 
  * Fixed.

Awesome

* takeaway class is hardcoded to Dish - you could ease that relationship with some dependency injection? 
  * Done what I think is right, is this OK? I did it on the order method too.

yes that looks good - can you remove the Dish class from the takeaway_spec to in order to ensure the independence of the unit test?

Reek is still picking up some issues - particularly worried that TakeAway#order method is much too long?  Care to work through the reek issues?

Please to ask me if anything is unclear ...

**Comment by trwh** [comment]
Hi @tansaku, thanks for the feedback, I think I've addressed everything you raised. Would you consider marking this as complete?

Thanks again,

Tim

**Comment by tansaku** [comment]
thanks for the update @trwh - apologies for the delay in responding.  Everything still green with 100% coverage very good.  I'm still getting some local [Rubocop](https://github.com/bbatsov/rubocop) (what Hound uses, `gem install rubocop; rubocop -DS`) issues however:

```
$ rubcop
lib/takeaway.rb:15:3: C: Metrics/MethodLength: Method has too many lines. [6/5] (https://github.com/bbatsov/ruby-style-guide#short-methods)
  def see
  ^^^
lib/takeaway.rb:24:3: C: Metrics/MethodLength: Method has too many lines. [7/5] (https://github.com/bbatsov/ruby-style-guide#short-methods)
  def order(dishes, expected_total, meal_klass)
  ^^^
spec/meal_spec.rb:6:19: C: Style/BlockDelimiters: Avoid using {...} for multi-line blocks. (https://github.com/bbatsov/ruby-style-guide#single-line-blocks)
  let (:duck_dish){ double(:dish, see: "44 : Duck a la banana : £4.50 : 2",
                  ^
spec/meal_spec.rb:6:21: C: Style/MultilineBlockLayout: Block body expression is on the same line as the block start.
  let (:duck_dish){ double(:dish, see: "44 : Duck a la banana : £4.50 : 2",
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/meal_spec.rb:7:18: C: Style/BlockEndNewline: Expression at 7, 18 should be on its own line.
    total: 9.00) }
                 ^
spec/meal_spec.rb:8:19: C: Style/BlockDelimiters: Avoid using {...} for multi-line blocks. (https://github.com/bbatsov/ruby-style-guide#single-line-blocks)
  let (:deep_dish){ double(:dish, see: "10 : Deep fried Mars bar : £0.10 : 10",
                  ^
spec/meal_spec.rb:8:21: C: Style/MultilineBlockLayout: Block body expression is on the same line as the block start.
  let (:deep_dish){ double(:dish, see: "10 : Deep fried Mars bar : £0.10 : 10",
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/meal_spec.rb:9:18: C: Style/BlockEndNewline: Expression at 9, 18 should be on its own line.
    total: 1.00) }
```

and some [Reek](https://github.com/troessner/reek) (`gem install reek ; reek -U`) ones:

```
$ reek -U
lib/dish.rb -- 1 warning:
  [5]:Dish#quantity is a writable attribute (Attribute) [https://github.com/troessner/reek/blob/master/docs/Attribute.md]
lib/takeaway.rb -- 2 warnings:
  [32]:Takeaway#order is controlled by argument expected_total (ControlParameter) [https://github.com/troessner/reek/blob/master/docs/Control-Parameter.md]
  [18, 19, 21]:Takeaway#see refers to list more than self (maybe move it to another class?) (FeatureEnvy) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]
3 total warnings
```

your `sms.rb` file is empty and you have `sms_spec` as well - they both look like redundant files so they should be deleted.

Looking over the reek issues (which perhaps you didn't get locally) - thought I'd ask you to address them - I see you've added comments to all the classes - which is a reek warning you get when reek doesn't run with our makers config hmmm ....

* Either way as reek indicates attr_accessor on Dish is a smell.

* Not sure about the methods named `see`.  Ruby convention might suggest `to_s`?

* Takeaway#order and Takeaway#see are too long (as rubocop suggests) --> Takeaway#see could use inject to slim it down

* line 34 in Takeaway#order is a non-indented true statement - weren't we getting OCD about all this? :-)

* I don't think Takeaway#order should use inject and meal doesn't need to be an instance variable, at a first pass I'd clean up like this:

```ruby
  def order(dishes, expected_total, meal_klass)
    meal = meal_klass.new
    dishes.each do |dish|
      meal.add get_dish_object(dish)
    end
    fail 'You\'ve got the price wrong!' unless meal.total == expected_total
  end
```

but there's further to go such as making meal_klass be something that gets set in initialize rather than passed in via order.

I really appreciate all the work you're putting in to improve this, but I still have a few concerns that prevent me from saying it's completed.  

First up check you're getting the same rubocop/reek issues that I'm seeing - make sure you fix them up, and then I think we need to sit down and have a talk about the 'least power principle'.  What I'm seeing you do in several places is use far more programming power than you need, and then not using in other places where it could slim things down.  Prime example is the use of inject in Takeaway#order where it's not needed, but then not using it in Meal#total or Takeaway#see where it would be justified and help clean things up.

Have another pass and come find me next week so we can look at this together.  I'm in the office Mon, Wed, Fri and am available remotely Tues/Thurs.

**Comment by tansaku** [comment]
oh and the other thing is that your irb preview in the README doesn't really show the full functionality - we should look at that too ...

**Comment by tansaku** [comment]
will be happy to review further updates when you submit @trwh :-)

**Pull request closed without merging**
