### PR TITLE
Joe Zhou Takeaway Challenge - 2

### PR DESCRIPTION
**Pull request by chn-challenger**

### CODE REVIEW

**Comment by tansaku** [comment]
@chn-challenger you said you had a review from @sanjsanj on this already?

**Comment by chn-challenger** [comment]
I haven't fixed it yet sorry Sam, please look at my inject and rps instead, I will update this this weekend

**Comment by tansaku** [comment]
sure thing :-)

**Comment by tansaku** [comment]
Hey @chn-challenger some great work here; tests green and 100% coverage - some tips to help you improve

* Well done updating your README. Also note it's a great idea to show the full story of how your app is used (from a user's perspective) in the README, e.g. an irb transcript

```sh
$ irb
2.2.3 :001 > dish1 = Dish.new('Egg Rice',3.2)
 => #<Dish:0x007f9657093bd0 @name="Egg Rice", @price=3.2> 
2.2.3 :002 > dish2 = Dish.new('Chicken Curry',4.5)
 => #<Dish:0x007f9657089bd0 @name="Chicken Curry", @price=4.5> 
2.2.3 :003 > dish3 = Dish.new("Joe's Special",11.99)
 => #<Dish:0x007f965707b2b0 @name="Joe's Special", @price=11.99> 
2.2.3 :004 > menu = Menu.new("Joe's Menu")
 => #<Menu:0x007f96570719e0 @name="Joe's Menu", @dishes=[]> 
2.2.3 :005 > menu.add_dish(dish1)
 => [#<Dish:0x007f9657093bd0 @name="Egg Rice", @price=3.2>] 
2.2.3 :006 > menu.add_dish(dish2)
 => [#<Dish:0x007f9657093bd0 @name="Egg Rice", @price=3.2>, #<Dish:0x007f9657089bd0 @name="Chicken Curry", @price=4.5>] 
2.2.3 :007 > menu.add_dish(dish3)
 => [#<Dish:0x007f9657093bd0 @name="Egg Rice", @price=3.2>, #<Dish:0x007f9657089bd0 @name="Chicken Curry", @price=4.5>, #<Dish:0x007f965707b2b0 @name="Joe's Special", @price=11.99>] 
2.2.3 :008 > joes_takeaway = TakeAway.new(menu)
 => #<TakeAway:0x007f9657050f10 @menu=#<Menu:0x007f96570719e0 @name="Joe's Menu", @dishes=[#<Dish:0x007f9657093bd0 @name="Egg Rice", @price=3.2>, #<Dish:0x007f9657089bd0 @name="Chicken Curry", @price=4.5>, #<Dish:0x007f965707b2b0 @name="Joe's Special", @price=11.99>]>, @orders=[]> 
2.2.3 :009 > joes_takeaway.menu.dishes.count
 => 3 

```

I inferred the above from your feature test, but not every user will know to do that ...


* let's have a look at a few things that [Reek](https://github.com/troessner/reek) (`gem install reek ; reek -U`) and [Rubocop](https://github.com/bbatsov/rubocop) (what Hound uses, `gem install rubocop; rubocop -DS`) have to say about your code:

> lib/menu.rb -- 5 warnings:
  [33, 33]:Menu#display_menu_title calls " " * side_spacing 2 times (DuplicateMethodCall) [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
  [38, 38]:Menu#wrong_name? calls dish.name 2 times (DuplicateMethodCall) [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
  [37, 38, 38]:Menu#wrong_name? refers to dish more than self (FeatureEnvy) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]
  [43, 43]:Menu#wrong_price? calls dish.price 2 times (DuplicateMethodCall) [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
  [42, 43, 43]:Menu#wrong_price? refers to dish more than self (FeatureEnvy) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]
lib/order.rb -- 4 warnings:
  [74, 75]:Order#line_part_i calls dish_hash[:dish] 2 times (DuplicateMethodCall) [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
  [73]:Order#line_part_i doesn't depend on instance state (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
  [80]:Order#line_part_ii doesn't depend on instance state (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
  [35]:Order#shorten_spaces doesn't depend on instance state (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
lib/text_messenger.rb -- 4 warnings:
  [18]:TextMessenger#delivery_time doesn't depend on instance state (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
  [22]:TextMessenger#twillio_account_sid doesn't depend on instance state (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
  [26]:TextMessenger#twillio_auth_token doesn't depend on instance state (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
  [30]:TextMessenger#twillio_phone_number doesn't depend on instance state (UtilityFunction) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
14 total warnings

Note that the instance state (Utility Function) warnings are suggestions that these are elements that could be in modules.  Note that TextMessenger does not actually need any instance state --> convert to a module?

> lib/dish.rb:24:20: C: Style/FormatString: Favor format over String#%. (https://github.com/bbatsov/ruby-style-guide#sprintf)
    price = '%.2f' % @price
                   ^
lib/order.rb:61:3: C: Metrics/AbcSize: Assignment Branch Condition size for display_order_total is too high. [18.03/15] (http://c2.com/cgi/wiki?AbcMetric)
  def display_order_total
  ^^^
lib/order.rb:63:20: C: Style/FormatString: Favor format over String#%. (https://github.com/bbatsov/ruby-style-guide#sprintf)
    total = '%.2f' % order_total
                   ^
lib/order.rb:73:3: C: Metrics/AbcSize: Assignment Branch Condition size for line_part_i is too high. [15.3/15] (http://c2.com/cgi/wiki?AbcMetric)
  def line_part_i(dish_hash)
  ^^^
lib/order.rb:75:5: C: Style/MultilineOperationIndentation: Align the operands of an expression in an assignment spanning multiple lines.
    dish_hash[:dish].price.to_s + " x " + dish_hash[:quantity].to_s
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/order.rb:81:26: C: Style/FormatString: Favor format over String#%. (https://github.com/bbatsov/ruby-style-guide#sprintf)
    total_price = '%.2f' % (dish_hash[:dish].price * dish_hash[:quantity])
                         ^
lib/text_messenger.rb:5:3: C: Metrics/MethodLength: Method has too many lines. [8/5] (https://github.com/bbatsov/ruby-style-guide#short-methods)
  def send_order_text number, order
  ^^^


* Note that you are using `require` throughout your ruby files in your lib directory - these are preventing me from running things from irb.  They should all be require_relative:

```sh
→ irb
cannot load such file -- line_length
2.2.3 :001 > dish1 = Dish.new('Egg Rice',3.2)
NameError: uninitialized constant Dish
	from (irb):1
	from /Users/tansaku/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'
2.2.3 :002 > exit
[tansaku@Samuels-MacBook-Pro:~/Documents/Github/MakersAcademy/takeaway-challenge ((c893b5c...))]$ 
→ irb
2.2.3 :001 > dish1 = Dish.new('Egg Rice',3.2)
 => #<Dish:0x007f9657093bd0 @name="Egg Rice", @price=3.2> 
```

* Great that you have a feature test, but you have a lot of setup happening in the clear between it blocks - this should all be in `lets` and/or `before` blocks - you've done it correctly in order_spec.rb ...

The [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter) suggests that:

* Each object should have only limited knowledge about other units: only units "closely" related to the current unit.
* Each object should only talk to its friends; don't talk to strangers.
* Only talk to your immediate friends.

The following test shows a process of reaching through a series of related objects.  The warning sign is the multiple periods in `joes_takeaway.menu.dishes.include?`.  Here we are seeing takeaway is being tested for properties that belong to the menu - effectively they are none of restaurant's business and shouldn't be tested here; and we shouldn't be seeing chains like this in application code either

```ruby
  scenario "The menu contains a dish that was added to it" do
    expect(joes_takeaway.menu.dishes.include?(dish3)).to eq(true)
  end
```

we should prefer to ask the takeaway through a single method like so:

```ruby
  scenario "The menu contains a dish that was added to it" do
    expect(joes_takeaway.all_dishes).to include dish3
  end
```

* This is a unit test and not a feature test:

```ruby
  text_messenger = TextMessenger.new

  scenario "Can send a text with order confirmation to the customer" do
    expect(text_messenger).to respond_to(:send_order_text).with(2).argument
  end
```

* RSpec provides a [`subject`](https://www.relishapp.com/rspec/rspec-core/docs/subject/explicit-subject) method that creates a new instance of the class under test (the one following `describe`), so this:

```
describe Dish do
  describe "#initialize/new" do
    it "can make a new dish of name 'egg fried rice' with price of 4.50" do
      new_dish = Dish.new('egg fried rice', 4.50)
      expect(new_dish.name).to eq('egg fried rice')
      expect(new_dish.price).to eq(4.50)
    end
  end
end
```

can become

```
describe Dish do
  describe "#initialize/new" do
    subject { Dish.new('egg fried rice', 4.50) }
    it "can make a new dish of name 'egg fried rice' with price of 4.50" do
      expect(subject.name).to eq('egg fried rice')
      expect(subject.price).to eq(4.50)
    end
  end
end
```

and similarly for your other tests


* In Menu your fail messages could be a little more descriptive than just "invalid" - why not say why the thing is invalid?

* Good use of doubles in menu_spec

* Has Order got too many responsibilities?

Great work here Joe.  I've given you a pretty thorough review as I know you have high standards.  I'm happy to give you a sticker just for your effort and initiative of getting the review from @sanj and letting me know I could hold off.   However if you want me to hold you to a higher standard and wait to give you a sticker until you've fixed some of the above, I'm very happy to do so :-)

:construction:

**Comment by chn-challenger** [comment]
Hi Tansaku, thank you for the detailed review, this is invaluable and I really appreciate it.  I want to make the code as good as I can make it, so I will definitely fix and rework according to the points you made above.  I am not too concerned with the sticker at this point, but it would be great if you could take another look at the code once I finished reworking it.  :)

**Pull request closed without merging**
